[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "e22692eeca5682143433ca82feed23f6af7d0f3b"
os = "macos"

    [[GDAL.download]]
    sha256 = "84e2badfa1dea1013bfc07815880890ae5416bd32e3de4cf6b3569392d7afb6b"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.aarch64-apple-darwin.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a41a3e95396cd2fa2a3eb7d19562cd49487cc64"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "8006c6e7cf9aeee60b4a7f01966ecf02b3d88fa03e9455393d3541a8dc20371b"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.aarch64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eebf1ad488d17505d6f7a364f6db1b2bb4d0b3c7"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "7c4efd51ee7c459cb36167f443dccb39867c827747f351e728a19053794a90ad"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.aarch64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "aarch64"
git-tree-sha1 = "6c716f6fde084d9fde8ce2d60498842c23478ae3"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "1904a5c105939ba33414f2e557356062ecf4017fa4b9c50c415cd46ba8bb2a10"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.aarch64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b1fb7ac85f5baf3d4b919edcbccfa322b8049d5"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "ef5fe94cddcaa405cc66bf4a07ca4ac3bfb364702737ee2243c085a6b18dd487"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3f10c884a6cb24633c9df2b31e6cd39aea3861e"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "0df969da704f8ef4d15ac466aa6e1a61d94bcbd06e9bdde8740387f1ac19b013"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c34d7b8b503d70d4f10b42cd4d1551d0e845efbd"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "408536857aeb9158acdec867cd38098fcd7c660b153d34141c4dba8759941406"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8adf0e0c7fcd093925d7e4b82eecbefcceace8e7"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "f311850d96eb76e1e0635c5b424e85ad060d343b2ed36063917e73233fff019c"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01f42147a6eea52a766eff503c6ce93db703f370"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "7287089b0d91c156e74673208cd09aa526745ddf1ccd6901eda9f79250d293b0"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.i686-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "350f26abf8606b582ea8f50ec0dd138d41398059"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "46badd982ffd96de0150bf4b184c89fef5c89fa8c630d2019131663c358b7154"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.i686-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "023f31df0eb22f52d8289678a95dcdaa74a36f89"
os = "windows"

    [[GDAL.download]]
    sha256 = "5ce91cc72dade35134691685cc0cd0b899677ccffc8fffcfcdef4f49f5aa93c5"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.i686-w64-mingw32-cxx11.tar.gz"
[[GDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c538dbfdf476c60672cbdd8323e0ad215601faaf"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "c0e70e87d63cd28b66d97261e3c9ad61e6f450a0390a01135505e6aefb616c4a"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f320da938985c0adc08a92c99b6ba92550fb6b7d"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "badccdb3c3f6ec398ccf38a3135ac85250edbd7497a7444b54fbd2e25bc4a078"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.riscv64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "16c250438252ea9f8c0387e1ee17761b22c379ec"
os = "macos"

    [[GDAL.download]]
    sha256 = "a2011d4a43de13d52bf24cb185eeebf58c9166dc3711f0d6c4646780e04cad89"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.x86_64-apple-darwin.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "842ddddcd6726ba73b9a577c27fc9aac323b709b"
libc = "glibc"
os = "linux"

    [[GDAL.download]]
    sha256 = "35680248139f83ed53700a1cec4e5242f0d5ebd6d6a2a68052863111cbe3957e"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.x86_64-linux-gnu-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72f6e07f477224f6ad1eddd856f2400b947cb58a"
libc = "musl"
os = "linux"

    [[GDAL.download]]
    sha256 = "ac677aaea68b8cbb856dce1d9bb7e38140ccd526d41a1c1bf6a4005adfd55e3e"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.x86_64-linux-musl-cxx11.tar.gz"
[[GDAL]]
arch = "x86_64"
git-tree-sha1 = "5485825fa2e9e1e7a14510dec69d6d79daa3c7f1"
os = "freebsd"

    [[GDAL.download]]
    sha256 = "716381b0ee0039039c01cf407f3ddbf2ba24ef10d2a787a73a33b3e1159a34c7"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.x86_64-unknown-freebsd.tar.gz"
[[GDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f4cf7eeef1f84573a5add9d5b7387d6c8ff5005"
os = "windows"

    [[GDAL.download]]
    sha256 = "85fb9ca84b5bee0b89e1e20010cdc5695e56fe26b0a5ac010d0874d4cf8b1c11"
    url = "https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases/download/GDAL-v304.1200.400+0/GDAL.v304.1200.400.x86_64-w64-mingw32-cxx11.tar.gz"
